name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Go tests
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Test
        run: go test ./...

  build-image:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Commit Count as Version
        id: get_version
        run: |
          # This counts the number of commits in the current branch (e.g. main)
          version=$(git rev-list --count HEAD)
          echo "Commit count version: $version"
          echo "version=commit-$version" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/traefik-forward-auth
          docker build -t $IMAGE_NAME:${{ steps.get_version.outputs.version }} .

      - name: Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/traefik-forward-auth
          docker push $IMAGE_NAME:${{ steps.get_version.outputs.version }}
